repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # Your other hooks...
  - repo: local
    hooks:
      - id: check_cpp_functions
        name: Check C++ Functions
        entry: check.ps1
        language: script
        types: [cpp]
